fix(ReporterUtils): filename extraction for component testing
BBE78/cypress-sonarqube-reporter pull request #47
Opened 2023-09-19 08:06 UTC by Sett17

Fixes an issue with extracting the spec filename from the suite in component testing. The code now properly handles cases where the requested spec is not available and falls back to using the parent suite's file as the spec filename.

Fixes #46

2023-09-20 10:19 UTC, BBE78 requested changes

2023-09-20 10:19 UTC, BBE78 commented on src/ReporterUtils.js
> +    } else if (suite.invocationDetails && (suite.invocationDetails.absoluteFile || suite.invocationDetails.relativeFile)) {
Prefer the usage of optional chaining in that case
```javascript
else if (suite.invocationDetails?.absoluteFile || suite.invocationDetails?.relativeFile)
```

2023-09-20 10:19 UTC, BBE78 commented on src/ReporterUtils.js
> +    } else if (suite.parent && suite.parent.file) {
Prefer the use of optional chaining:
```javascript
else if (suite.parent?.file)
```

2023-09-20 10:19 UTC, BBE78 commented on src/ReporterUtils.js
Add a test case with a Cypress component test to verify the modification

2023-09-20 10:21 UTC, BBE78 commented
Hi @Sett17, thanks for your code fix proposal. Could you please setup a test case with Cypress component test to cover this fix?

2023-09-20 11:01 UTC, Sett17 commented
> Hi @Sett17, thanks for your code fix proposal. Could you please setup a test case with Cypress component test to cover this fix?

Hey, do you mean actually adding a minimal app with a ct that can be tested? Or just another case in the `ReporterUtils.spec.js`

2023-09-20 11:02 UTC, Sett17 commented on src/ReporterUtils.js
Hey, do you mean actually adding a minimal app with a ct that can be tested? Or just another case in the ReporterUtils.spec.js

2023-09-21 11:34 UTC, fcuenya commented on src/ReporterUtils.js
It seems like only the later would be feasible, as the only way to fully reproduce the original issue would be setting up a sample project with CTs and running the reporter on it. 

That would likely fall outside of the testing scope for this codebase, but I would like to know if you think otherwise.

I am having this exact same issue with the usage of this tool and would really appreciate to get this fix going through, that is why I decided to chime in 🙂

2023-09-21 12:45 UTC, fcuenya approved these changes

2023-09-25 07:38 UTC, Sett17 commented on src/ReporterUtils.js
@BBE78 Hey, any thoughts on this? If you'd like a minimal app in this, some guidance on where and how that should live would be appreciated.

2023-10-04 10:53 UTC, BBE78 commented on src/ReporterUtils.js
Hi @Sett17, a Jest test on the reporter is a good start point but not enough to me because it is not executed into a Cypress env.
Since it seems to be linked to Cypress Component tests, then a dedicated spec should be created to verify that the problem is correctly addressed by this fix

2023-10-06 10:35 UTC, Sett17 commented
@BBE78 I hope I understood you correctly and that this is what you are looking for.

2023-10-06 17:40 UTC, BBE78 commented
Great @Sett17 ! Looks good to me.
Maybe we could add something inside the README to say that with this PR, the reporter is now compatible with Cypress component testing, no ?

2023-10-10 07:46 UTC, merged