fix(MergeReports): use new syntax for fast-xml-parser
BBE78/cypress-sonarqube-reporter pull request #59
Opened 2024-07-16 11:43 UTC by tiimonn

2024-07-16 14:03 UTC, tiimonn commented
regarding #44 and #58
could the checks get approved? @BBE78 @Sett17

2024-08-30 17:11 UTC, BBE78 requested changes
Could you please fix the 2 comments ?

2024-08-30 17:11 UTC, BBE78 commented on package.json
> +        "fast-xml-parser": "^4.2.5",
Could you please bump to the latest v4.4.1 version of "fast-xml-parser" ?

2024-08-30 17:11 UTC, BBE78 commented on yarn.lock
Could you please use "https://registry.npmjs.org" registry instead of "https://registry.yarnpkg.com" to keep coherence with the other dependencies ?

2024-09-03 18:58 UTC, BBE78 approved these changes

2024-09-03 18:59 UTC, merged