support invocationDetails of cypress
BBE78/cypress-sonarqube-reporter pull request #9
Opened 2021-03-03 19:10 UTC by Franckrst

I show we can have all information for unit test report in invocationDetails of suite.
So we can use it ?

2021-03-03 19:40 UTC, BBE78 commented on src/ReporterUtils.js
> +    hasSpecInTitle
Provide a test to this new exported function (see test\specs\ReporterUtils.spec.js)

2021-03-03 20:08 UTC, BBE78 requested changes
Please update the `README` to describe the new feature: from what I understood, Mocha provide an `invocationDetails` property that could contain the same information and make the `specTitle` useless.
I could not find any description about the `invocationDetails` property on Mocha: could you please provide a link to its documentation and products version

2021-03-03 20:08 UTC, BBE78 commented on src/SonarQubeCypressReporter.js
> +            } else {
Provide a test case that demonstrate this branch

2021-03-03 23:31 UTC, Franckrst commented
> I could not find any description about the `invocationDetails` property on Mocha: could you please provide a link to its documentation and products version

I don't show documentation about `invocationDetails` but we can see it in cypress code : https://github.com/cypress-io/cypress/search?o=asc&q=invocationDetails&s=indexed

2021-03-03 23:56 UTC, Franckrst commented
i make all change you want. But for the readme i have very bad english, ca you make modification ?

2021-03-04 08:40 UTC, Franckrst commented
i dont understand why travis fail. I have no fail on my machine

2021-03-09 20:29 UTC, BBE78 commented
> i dont understand why travis fail. I have no fail on my machine

Troubles with Yarn cache and Cypress...

2021-03-09 20:41 UTC, BBE78 commented
I have some troubles with your PR: the test did not work on my env.
![image](https://user-images.githubusercontent.com/5666567/110535166-3733a480-8120-11eb-8cee-5e47c73e70dc.png)

2021-07-13 16:35 UTC, BBE78 commented
@Franckrst without any news from your side, I'll reject this PR...

2022-02-19 14:09 UTC, BBE78 commented
No news from author @Franckrst since too many months, rejecting this PR

2022-02-19 14:09 UTC, closed without merging